### PR TITLE
add 404 route for all non matching api routes

### PR DESCRIPTION
**Pull request by xqwtsz**
## Add 404 Route 😎

we now have a generic 404 route for all non matching _api_ routes

### CODE REVIEW

**Comment by xqwtsz** [comment]
🤦‍♂️ it's actually giving a 404 for every request, even thou the data from db is there.. looking into it now..

**Comment by xqwtsz** [comment]
🤦‍♂️ fixed the 404 for every request, i forgot that we dont send a res when there is a matching route, we just add things to `res.locals.response`, so i added a check to see if there is anything in there before pulling the good old **404** out

**Comment by kruemmelkhanh** [comment]
Stefan change a couple of things, please merge the dev in your branch

**Comment by kruemmelkhanh** [comment]
fix #87

**Pull request merged**
