### PR TITLE
Feature/bookmarkapi 60 addvalidatefeature

### PR DESCRIPTION
**Pull request by ctocco**
#60 validating included for URLs

### CODE REVIEW

**Comment by Bilie** [comment]
Hi, just fyi, here we use `develop` as main branch, so we should base all PRs on develop

**Comment by ctocco** [comment]
thanks will keep an eye on that next time!

**Comment by ctocco** [comment]
@sit79 can you please merge once you have review code. Thanks!

**Comment by sit79** [comment]
Fixes #60

**Pull request merged**
